package com.charles.trailsage.ui.screens.story

import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Pause
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewModelScope
import com.charles.trailsage.data.local.StoryEntity
import com.charles.trailsage.data.local.TrailSageDao
import com.charles.trailsage.map.StopLocationMap
import com.charles.trailsage.tts.NarrationPlayer
import com.charles.trailsage.ui.components.*
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class StoryDetailViewModel @Inject constructor(
    savedStateHandle: SavedStateHandle,
    private val dao: TrailSageDao,
    private val player: NarrationPlayer,
) : ViewModel() {
    private val storyId: String = savedStateHandle["storyId"] ?: ""

    private val _story = MutableStateFlow<StoryEntity?>(null)
    val story: StateFlow<StoryEntity?> = _story.asStateFlow()
    private val _location = MutableStateFlow<Pair<Double, Double>?>(null)
    val location: StateFlow<Pair<Double, Double>?> = _location.asStateFlow()
    val playing: StateFlow<Boolean> = player.playing

    init {
        viewModelScope.launch {
            _story.value = dao.story(storyId)
            dao.triggerForStory(storyId)?.let { _location.value = it.latitude to it.longitude }
        }
    }

    fun togglePlay() { _story.value?.let { player.toggle(it.narrationText) } }
    override fun onCleared() { player.stop() }
}

@Composable
fun StoryDetailScreen(onBack: () -> Unit, vm: StoryDetailViewModel = hiltViewModel()) {
    val story by vm.story.collectAsStateWithLifecycle()
    val playing by vm.playing.collectAsStateWithLifecycle()
    val location by vm.location.collectAsStateWithLifecycle()

    DetailScaffold(story?.title ?: "Story", onBack) {
        val current = story
        if (current == null) {
            EmptyStateCard("Story not loading", "Open a story from Explore, or install/generate a tour first.")
        } else {
            if (current.imageLocalPath.isNotBlank()) {
                Box(Modifier.fillMaxWidth().height(200.dp).clip(MaterialTheme.shapes.large)) {
                    TrailImage(current.imageLocalPath, current.title, Modifier.matchParentSize())
                }
            }
            location?.let { (lat, lon) ->
                SectionHeader("On the map")
                Box(Modifier.fillMaxWidth().height(180.dp).clip(MaterialTheme.shapes.large)) {
                    StopLocationMap(lat, lon, current.title, Modifier.matchParentSize())
                }
            }
            InfoCard("Narration", current.narrationText.ifBlank { "No narration text available for this stop." })
            Button(
                onClick = vm::togglePlay,
                modifier = Modifier.fillMaxWidth().height(56.dp),
                shape = MaterialTheme.shapes.small,
            ) {
                Icon(if (playing) Icons.Default.Pause else Icons.Default.PlayArrow, null)
                Spacer(Modifier.width(8.dp))
                Text(if (playing) "Pause narration" else "Play narration")
            }
            if (current.generatedByAi) {
                SourceChip("Narration generated by on-device AI")
            }
            SourceChip("Public-source content")
        }
    }
}
